<?php declare(strict_types=1); ?>
<form method="POST" action="/login">
    <div class="form-group">
        <input class="form-control" placeholder="Username" name="username" type="text">
    </div>
    <div class="form-group">
        <input class="form-control" placeholder="Password" name="password" type="password">
    </div>
    <div class="form-group">
        <div class="row">
            <div>
                <button type="submit">Login</button>
            </div>
        </div>
    </div>
</form>
