<?php declare(strict_types=1); ?>
<form method="POST" action="/login" class="login">
    <h1>Jeeves</h1>
    <div class="form-group">
        <input class="form-control" placeholder="Username" name="username" type="text">
    </div>
    <div class="form-group">
        <input class="form-control" placeholder="Password" name="password" type="password">
    </div>
    <div class="form-group">
        <button type="submit">Login</button>
    </div>
</form>
